basePath: /
definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  github_com_xjncx_people-info-api_internal_dto.PersonListResponse:
    properties:
      people:
        items:
          $ref: '#/definitions/github_com_xjncx_people-info-api_internal_dto.PersonResponse'
        type: array
    type: object
  github_com_xjncx_people-info-api_internal_dto.PersonResponse:
    properties:
      age:
        type: integer
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      last_name:
        type: string
      middle_name:
        type: string
      nationality:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API для получения информации о человеке (возраст, пол, национальность)
  title: People Information API
  version: "1.0"
paths:
  /people/search:
    get:
      consumes:
      - application/json
      parameters:
      - description: Фамилия
        in: query
        name: last_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_xjncx_people-info-api_internal_dto.PersonListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Поиск людей по фамилии
      tags:
      - People
swagger: "2.0"
